config/routes.rb
Rails.application.routes.draw do
  get "home" => 'static#home'

  get "portfolio" => 'static#portfolio'

  get "services" => 'static#services'

  get "about_us" => 'static#about_us'

  get 'static/insights'

  get "contact" => 'static#contact'

  root :to => 'static#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def portfolio
  end

  def services
  end

  def about_us
  end

  def insights
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_footer.html.erb
<footer id="footer" style="display: block;">
	<div class="container">

		<div class="row">
			<div class="col-12"><div style="height: 45px;"></div></div>
		</div>
		<div class="row footer-bot">
			<div class="col-lg-4 col-xs-12 col-sm-4 farea1 mob-center">
				<p class="footer-title mservice">Our core services</p>
				<ul>
					<li><a href="/creative-web-and-ui-design.php">Creative Web and UI Design</a></li>
					<li><a href="/web-and-mobile-development.php">Web and Mobile Development</a></li>
					<li><a href="/search-engine-optimization.php">Search Engine Optimization</a></li>
					<li><a href="/brand-identity.php">Brand Identity</a></li>
					<li><a href="/social-media-management.php">Social Media Management</a></li>
					<li><a href="/web-content-and-copywriting.php">Web Content</a></li>
				</ul>
			</div>

			<!-- INSIGHTS TEASERS -->
		<div class="col-lg-4 col-xs-12 col-sm-4 lr-border farea2">
			<p class="footer-title mservice">Latest Insights</p>
	    	<div class="blog-teasers widget">
	    		<div class="blog-teasers-inner mob-center">
	    			<ul>
	    											<li>
	    						<h3><a href="/insights/details.php?id=78">Holiday Shopping Trends 2015: 3 Predictions for Retailers</a></h3>
							</li>
														<li>
	    						<h3><a href="/insights/details.php?id=74">Make your brand social, across the web</a></h3>
							</li>
														<li>
	    						<h3><a href="/insights/details.php?id=70">5 Questions to Ask Yourself Before You Devote More Time to Social Media</a></h3>
							</li>
														<li>
	    						<h3><a href="/insights/details.php?id=13">Missing Mobile Compatibility? 3 Steps to Take Today</a></h3>
							</li>
														<li>
	    						<h3><a href="/insights/details.php?id=11">WordPress Security and why you should care</a></h3>
							</li>
								    			</ul>
	    		</div>
	    	</div>
	    </div>
<!-- EO INSIGHTS TEASERS -->
			<!--<div class = "col-lg-4 col-xs-12 col-sm-4 lr-border farea2">
				<p class="footer-title mservice">Latest from our blog</p>
				<ul>
					<li><a href="#">Transfering large files made simple and secure</a></li>
					<li><a href="#">Adding music or audio on your website, blog or social media site</a></li>
					<li><a href="#">Adding music or audio on your website, blog or social media site</a></li>
				</ul>
			</div>-->
			<div class="col-lg-4 col-xs-12 col-sm-4 farea3 mob-center">
				<p class="footer-title mservice">Get In Touch</p>
				<p>Toronto : <b>(416) 900-0869</b></p>
				<a href="/get-in-touch.php" class="footer-contact">+ Contact Us</a>
				

				<hr>
				<p><b>Existing Clients</b></p>
				<a href="https://books.zoho.com/portal/silentblastinc/login" class="footer-contact">+ Client Portal</a><br>
				<a href="/hosting-support.php" class="footer-contact">+ Hosting &amp; Technical Support</a>


				<div class="mcontact social">
					<p class="mob-center">
						<a href="http://www.facebook.com/silentblastinteractive"><i class="fa fa-facebook"></i></a>
						<a href="https://twitter.com/#!/silentblast"><i class="fa fa-twitter"></i></a>
						<a href="https://plus.google.com/109335371201079665242/about"><i class="fa fa-google-plus"></i></a>
						<a href="http://pinterest.com/silentblast/"><i class="fa fa-pinterest-p"></i></a>
						<a href="https://instagram.com/silentblast/"><i class="fa fa-instagram"></i></a>
					</p>
				</div>
			</div>
		</div>


	</div>
	<script type="text/javascript">
		var url = window.location;
		// Will only work if string in href matches with location
		$('ul.nav a[href="'+ url +'"]').parent().addClass('active');
	</script>

	<script type="text/javascript">
		$(".port-item").hover(function () {
		 $(this).find(".port-hover").fadeTo(50, 1);
		},
		function(){
		    $(this).find(".port-hover").fadeTo(50, 0);
		});
	</script>

	<script type="text/javascript">
		$(document).ready(function() {
			$("select").selectpicker({style: 'btn-hg btn-primary', menuStyle: 'dropdown-inverse'});

			// style: select toggle class name (which is .btn)
			// menuStyle: dropdown class name

			// You can always select by any other attribute, not just tag name.
			// Also you can leave selectpicker arguments blank to apply defaults.
		});
	</script>

</footer>

app/views/layouts/_header.html.erb
<div id="head-bg" class="hidden-sm">
	<div class="container">
		<div class="row">
			<div class="navbar navbar-inverse">
				<div class="col-lg-3 col-xs-12 col-sm-3">
					<a class="logo mlogo" href="/">
						<%= image_tag "logo1.png", alt: "" %>
					</a>
				</div>

				<div class="col-lg-9 col-xs-12 col-sm-9">
          <div class="nav-collapse pull-right">
						<ul class="nav navbar-nav">
							<li><%= link_to "Home", root_url %></li>
							<li><%= link_to "Portfolio", portfolio_url %></li>
							<li><%= link_to "Services", services_url %></li>
							<li><%= link_to "About Us", about_us_url %></li>
						<!-- 	<li><a href="/insights/">insights</a></li> -->
							<li><%= link_to "Get in Touch", contact_url %></li>

						</ul>
					</div><!-- /.nav-collapse -->


				</div>
			</div>
		</div><!-- EO row -->
	</div><!-- EO container -->
</div>


<div id="head-bg" class="visible-sm">
	<div class="container">
		<div class="row">
			<div id="lwd_mobile_pop_nav" class="phone-menu sm-nav" style="right: -185px;">
				<a href="#" class="pull-left menu-btn">
					<%= image_tag "menu-btn.png", alt: "" %>					
					</a>
				<div class="menu" style="height: 311px;">
					<%= link_to root_url, class: "menu-item", style: "line-height: 38px; height: 38px;" do %>
						<div class="menu-item-inner">
							<i class="fa fa-home"></i> Home
						</div>
					<% end %>

					<%= link_to portfolio_url, class: "menu-item", style: "line-height: 38px; height: 38px;" do %>
						<div class="menu-item-inner">
							<i class="fa fa-suitcase"></i> Portfolio
						</div>
					<% end %>

					<%= link_to services_url, class: "menu-item", style: "line-height: 38px; height: 38px;" do %>
						<div class="menu-item-inner">
							<i class="fa fa-camera"></i> Services
						</div>
					<% end %>

					<%= link_to about_us_url, class: "menu-item", style: "line-height: 38px; height: 38px;" do %>
						<div class="menu-item-inner">
							<i class="fa fa-heart"></i> About Us
						</div>
					<% end %>

					<%= link_to contact_url, class: "menu-item", style: "line-height: 38px; height: 38px;" do %>
						<div class="menu-item-inner">
							<i class="fa fa-phone-square"></i> Get in Touch
						</div>
					<% end %>

					<div class="bottom-logo">
						<%= image_tag "logo-lg.png", alt: "" %>						
					</div>
				</div>
			</div>
			<div class="col-xs-8 col-sm-8">
				<a class="logo mlogo" href="/">
					<%= image_tag "logo.png", alt: "" %>
				</a>
			</div>

			<div class="col-xs-4 col-sm-4">

				&nbsp;

			</div>
		</div><!-- EO row -->
	</div><!-- EO container -->
</div>

<div class="header-height"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="HandheldFriendly" content="true">
    <!-- <meta name="google-site-verification" content="Ysx1l996xH5jHvtvlfR90twbnvr_P5hoQdRclyS2Sts"> -->

    <%= favicon_link_tag 'favico.png', sizes: "32x32" %>  

    <meta name="keywords" content="Toronto web design company creative agency">  <meta name="description" content="A Toronto web design company that offers professional custom web design, web development and search engine optimization services. Call 416-900-0869"> 
    <!-- Open Graph tags -->
      
    
    <!-- <meta name="google-site-verification" content="3Zi8qLm2kMlnsKXIDvuUcOheZg3PuzA6uaGezsnKCfE"> -->

    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700,300,200,100" rel="stylesheet" type="text/css">

    <title>SquareShuttle</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <% yield(:css) %>
    
    <%= javascript_include_tag 'modernizr', 'application', 'data-turbolinks-track' => 'reload' %>
    <%= yield(:javascript) %> 
  </head>

  <body>
    <div id="preloader" style="text-align: center; padding-top: 80px; display: none;">
      <%= image_tag "Preloader_3.gif", alt: "" %>      
      <br>Programming the flux capacitor...
    </div>
    <div id="main" style="display: block;">
      <%= render partial: 'layouts/header' %> 
      <%= yield %>
    </div>
    <%= yield(:out_main) %>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>